services:
  build:
    image: hanzi-ruby-lens-toolchain
    isolation: process
    volumes:
      - type: bind
        source: ../
        target: C:/app
      - cargo-target-v2:C:/app/src-tauri/target
      - node-modules-v2:C:/app/node_modules
    working_dir: C:/app
    command:
      [
        "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "C:/app/scripts/docker-build.ps1",
      ]

volumes:
  cargo-target-v2:
  node-modules-v2:
